# permissions for end users to view transforms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: transform-viewer-role
rules:
- apiGroups:
  - pipelines.gst.io
  resources:
  - transforms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pipelines.gst.io
  resources:
  - transforms/status
  verbs:
  - get
