# permissions for end users to edit transforms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: transform-editor-role
rules:
- apiGroups:
  - pipelines.gst.io
  resources:
  - transforms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pipelines.gst.io
  resources:
  - transforms/status
  verbs:
  - get
