name: Build

on:
  create:
    tags:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build Images
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Login to container reigstry
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

    - name: Get image version
      shell: bash
      run: |
        echo ::set-output name=tag::$([[ "${GITHUB_REF##*/}" == "main" ]] && echo latest || echo ${GITHUB_REF##*/})
      id: version

    - name: Build the manager docker image
      run: VERSION=${{ steps.version.outputs.tag }} make docker-build

    - name: Build the gstreamer docker image
      run: VERSION=${{ steps.version.outputs.tag }} make docker-gst-build

    - name: Push the manager docker image
      run: VERSION=${{ steps.version.outputs.tag }} make docker-push
      if: ${{ github.event_name != 'pull_request' }}

    - name: Push the gstreamer docker image
      run: VERSION=${{ steps.version.outputs.tag }} make docker-gst-push
      if: ${{ github.event_name != 'pull_request' }}
